### ISSUE TITLE
Assertions always pass

### ISSUE THREAD

**Issue by NaZaRKIN123** [jcoreio/chai-wait-for#3]
Hello,

I'm always getting all assertions passed which is not right.
I believe I'm doing all right. Please assist.

```
import { use } from 'chai'
import { After, Given, Then, When } from '@cucumber/cucumber'
import chai_wait_for, { bindWaitFor } from 'chai-wait-for'
use(chai_wait_for)
const waitFor = bindWaitFor({
  timeout: 5000,
  retryInterval: 100,
})

Given(/test/, function () {
  waitFor(() => {
    return { hello: 'abc' }
  }).to.deep.equal({ hello: 'def' })
  waitFor(() => 'abc').to.equal('def')
})
```

**Comment by jedwards1211** [comment]
Oh you'll always need to `await` your `waitFor` chains; they return a promise that resolves when the assertion succeeds, or rejects when it times out before success.

**Comment by jedwards1211** [comment]
So:

```ts
Given(/test/, async function () {
  await waitFor(() => {
    return { hello: 'abc' }
  }).to.deep.equal({ hello: 'def' })
  await waitFor(() => 'abc').to.equal('def')
})
```

(I don't know for sure if Cucumber supports Promise-returning test functions, but seems like it does)

**Comment by jedwards1211** [comment]
(I guess the TS error you were seeing confused you.  TypeScript was wrong in saying that `await` has no effect, because it didn't have the right type defs for this library.  My fix for #2 should have made it so that TS will no longer complain about the `await`.  If you're still seeing that error message I can reopen #2)

**Comment by NaZaRKIN123** [comment]
Sorry for the confusion, I thought the fix would be the opposite. Thanks, now with await it works fine.

**Comment by jedwards1211** [comment]
Okay great!
